config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :buses do
    resources :bus_services
    resources :drivers
  end
  resources :booking_seats do
    collection do
      get :sucess
      get :cancel
    end
  end
  get 'seats/show'
  patch 'seats/:id', to:"seats#update", as:"seat"
  get 'seats/:id/edit', to:"seats#edit", as:"edit_seats"
end

app/models/seat.rb
class Seat < ApplicationRecord
  enum seat_type: ['general', 'sleeper']
  belongs_to :bus
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  def show
    @bus = Bus.find_by_id(params[:bus_id])
    @booking = @bus.bookings.build
    @schedule = find_schedule(params[:schedule_id])
    @seat_name = @schedule.bookings.pluck(:seat_name)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @seat = Seat.find_by_id(params[:id])
  end

  def update
    @seat = Seat.find_by_id(params[:id])
    @bus = @seat.bus
    respond_to do |format|
      if @seat.update(seat_params)
        format.html { redirect_to bus_url(@seat.bus, bus_seat:"bus_seat"), notice: "Seat was successfully updated." }
        format.js
        # format.json { render :show, status: :ok, location: @seat }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@seat) }
      end
    end
  end

  private

  def seat_params
    params.require(:seat).permit(:name, :seat_type)
  end

  def find_schedule(params)
    key = params.present? ? 'id' : 'trip_date'
    value = params.present? ? params : Date.today
    @bus.schedules.find_by(key+' =?', value)
  end
end

app/helpers/seats_helper.rb
module SeatsHelper

  def get_schedules(bus)
    bus.schedules.where('trip_date >=?', Date.today)
  end

  def get_services(bus_service)
    str = ""
    str += "<div><i class='fa fa-wifi' aria-hidden='true' data-toggle='tooltip' data-placement='top' title='Wifi'></i> Wifi</div>" if bus_service.wifi?
    str += "<div><i class='fa fa-television' aria-hidden='true' data-toggle='tooltip' data-placement='top' title='Telivision'></i> Telivision</div>" if bus_service.tv?
    str += "<div><i class='fa-solid fa-toilet' aria-hidden='true' data-toggle='tooltip' data-placement='top' title='Toilet'></i> Washroom</div>" if bus_service.washroom?
    str += "<div><i class='fa fa-snowflake-o' aria-hidden='true' data-toggle='tooltip' data-placement='top' title='Air Conditioner'></i> Air Conditioner</div>" if bus_service.ac?
    str += "<div><i class='fas fa-cheeseburger' aria-hidden='true' data-toggle='tooltip' data-placement='top' title='Foods'></i> Food</div>" if bus_service.food?
    str += "<div><i class='fa-solid fa-blanket' aria-hidden='true'  data-toggle='tooltip' data-placement='top' title='Blanket'></i> Blanket</div>" if bus_service.blanket?
    str
  end
end

app/views/seats/_book_seat.html.erb
<h5 class="text-center">Available Seat</h5>
<div class="fuselage">
  
</div>
<ol class="cabin fuselage">
  <li class="p-2 driver-seat">
    <img src="https://james-muriithi.github.io/bus/images/driver.png">
  </li>
    <% index = 0%>
    <% @bus.seats.each_slice(5) do |seats|%>
        <li class="row row--<%= index += 1%>">
          <ol class="seats" type="A">
            <% seats.each do |seat|%>
              <li class="seat">
                <%= check_box_tag("seats[]", seat.name,false, {id:"#{seat.name}", onclick:"selectSeat(#{seat.name})", disabled: @seat_name.include?(seat.name) ? true: false}) %>
                <label for="<%= seat.name%>"><%= seat.name%></label>
              </li>
            <%end%>
          </ol>
        </li>
    <%end%>
</ol>
<div class="fuselage">
  
</div>

app/views/seats/_old_booking_seat.html.erb
<%= form_for @booking, url: booking_seats_path(@booking), method: :post do |f|%>
  <%= f.hidden_field :bus_id, value: @bus.id%>
  <%= f.hidden_field :schedule_id, value: @schedule.id%>
<!-- select seat -->
  <div id="select-seat step-2" class="form-step d-none">
    <div class="m-3 text-success text-center">
      <h5 id="date-of-journey m-2 text-success">
        Date of journey: <%= @schedule.trip_date.strftime("%d %h %Y")%>   
      </h5>
    </div>
    <div class="select-seat-left">
      <h5 class="text-center">Available Seat</h5>
      <div class="fuselage">
        
      </div>
      <ol class="cabin fuselage">
        <li class="p-2 driver-seat">
          <img src="https://james-muriithi.github.io/bus/images/driver.png">
        </li>
          <% index = 0%>
          <% @bus.seats.each_slice(5) do |seats|%>
              <li class="row row--<%= index += 1%>">
                <ol class="seats" type="A">
                  <% seats.each do |seat|%>
                    <li class="seat">
                      <%= check_box_tag("seats[]", seat.name,false, {id:"#{seat.name}", onclick:"selectSeat(#{seat.name})", disabled: @seat_name.include?(seat.name) ? true: false}) %>
                      <label for="<%= seat.name%>"><%= seat.name%></label>
                    </li>
                  <%end%>
                </ol>
              </li>
          <%end%>
      </ol>
      <div class="fuselage">
        
      </div>
    </div>
    <div class="clearfix" id="bus-seat-<%= @bus.id%>">
      <div class="select-seat-right row">
        <h5 class="text-center">Booking seat </h5>
        <div class="seat-details"></div>
      </div>
    </div>
    <div class="m-3">
      <!-- <button onclick="continueStep()" type="button" class="btn btn-success continue-step">continue</button> -->
      <button class="button btn-navigate-form-step" type="button" step_number="1">Prev</button>
      <button class="button btn-navigate-form-step" type="button" step_number="3">Next</button>
    </div>
  </div>

<!-- add passenger -->
  <div class="passenger-section form-step d-none" id="select-passenger step-3">
    <div class="passengers">   
      <%= f.fields_for :passengers do |passenger| %>
        <%= render 'passenger_fields', f: passenger %>
      <% end %>
    </div>
    <%= link_to_add_association "Add Passenger", f, :passengers, data: {association_insertion_node: '.passengers', association_insertion_method: :append} %>
    <button class="button btn-navigate-form-step" type="button" step_number="2">Prev</button>
    <%= f.submit 'save', class:"button submit-btn"%>
  </div>
<%end%>

<style type="text/css">

  li > a{
    text-decoration: none !important;
  }

  #select-seat{
    display: none;
    margin: 25px 210px;
    background: white;
    padding: 35px;
    border: 1px solid gainsboro;
    border-radius: 10px;
  }
  #select-passenger{
    display: none;
  }

  .select-seat-left{
    float: left;
    width: 45%;
  }

  .select-seat-right{
    float: right;
    width: 55%;
  }

  .clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/*.booking-section{
  display: none;
}
*/
#select-city, #select-passenger{
  margin: 47px 420px;
  max-width: 35%;
  border: 1px solid gainsboro;
  background: white;
  padding: 18px;
  border-radius: 10px;
}

.next-step{
  margin-left: 350px;
  }

.continue-step{
  float: right;
}
</style>

<script type="text/javascript">

  function selectSeat(params) {
    var checkBox = document.getElementById(params.id)
    if (checkBox.checked == true){
      $(".seat-details").append("<div id="+'seat-name-'+params.id+" class='border seat-name '>Economy Class Seat #"+params.id+": Ksh 3000 <button class='btn btn-danger close' onclick='unCheckSeat("+params.id+")' data-id="+params.id+">delete</button></div>")
    } 
    else {
      $('#seat-name-'+params.id).remove()
    }
  }

  //remove and unckecked seat through button
  function unCheckSeat(params) {
    var checkBox = document.getElementById(params.id)
    checkBox.checked = false
    $('#seat-name-'+params.id).remove()
  }

  function nextStep() {
    $('#select-city').hide()
    $('#select-seat').show()
    return false;
  }

  function continueStep() {
    $('#select-city').hide()
    $('#select-seat').hide()
    $('#select-passenger').show()
    return false;
  }
</script>

app/views/seats/_passenger_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="form-group mb-3 col-sm-6">
      <%= f.label :first_name, class: "mt-3" %>
      <%= f.text_field :first_name, class: 'mb-3 form-control'%>
    </div>
    <div class="form-group mb-3 col-sm-6">
      <%= f.label :last_name, class: "mt-3" %>
      <%= f.text_field :last_name, class: 'mb-3 form-control'%>
    </div>
  </div>

  <div class="row">
    <div class="form-group mb-3 col-sm-6">
      <%= f.label :age, class: "mt-3" %>
      <%= f.text_field :age, class: 'mb-3 form-control'%>
    </div>
    
    <div class="form-group mb-3 col-sm-6">
      <%= f.label :contact_no, class: "mt-3" %>
      <%= f.number_field :contact_no, class: 'mb-3 form-control'%>
    </div>
  </div>

  <div class="form-group mb-3">
    <%= f.label :address, class: "mt-3" %>
    <%= f.text_area :address, class: 'mb-3 form-control'%>
  </div>



  <%= link_to_remove_association "Delete", f %>
</div>

app/views/seats/edit.html.erb
<%= turbo_frame_tag "seat_name_#{@seat.id}" do %> 
  <%= form_with model: @seat, url: seat_path(@seat) do |form| %> 
    <%= form.text_field :name, class: "form-control", onchange:"this.form.submit()", :'data-remote' => 'true', :'data-type' => 'script'%>
    <%#= form.submit "Save" %> 
  <% end %> 
<% end %>
<%= turbo_frame_tag "seat_type_#{@seat.id}" do %> 
  <%= form_with model: @seat, url: seat_path(@seat), local: false, remote: true do |form| %> 
    <div><%= form.collection_select :seat_type, Seat.seat_types, :first, :first, {class: "form-control", onchange:"this.form.submit()"} %>
    </div>
  <% end %> 
<% end %>

<script type="text/javascript">
  function onChangeAction(){
     $.ajax({
      dataType: "script",
      type: "PATCH",
      url: "/seats/:id"+bus_id,
      data: { 
        schedule_id: schedule_id         
      }
    });
  }
</script>

app/views/seats/show.html.erb
<div id="booking_block" >
  <%= render 'booking' %>
</div>

app/views/seats/show.js.erb
var schedule  = document.getElementById('schedule_id')
schedule  = schedule.options[schedule.selectedIndex]
schedule.setAttribute('selected',true)
$('#booking_block').html("<%= j ( render 'booking' )%>")
var selected_data  = document.getElementById('schedule_id')
selected_data.options[selected_data.selectedIndex] = schedule

app/views/seats/update.js.erb
debugger
<%#= turbo_frame_refresh "seat_name_#{params[:id]}" %>
// $('#edit-bus-<%= @bus.id%>-seat').html("<%= j ( render 'buses/edit_bus_seat' )%>");