config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :buses do
    resources :bus_services
    resources :drivers
  end
  resources :booking_seats do
    collection do
      get :sucess
      get :cancel
    end
  end
  get 'seats/show'
  patch 'seats/:id', to:"seats#update", as:"seat"
  get 'seats/:id/edit', to:"seats#edit", as:"edit_seats"
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :authenticate_user!

  def index
    @buses = current_user.buses.order(created_at: :desc)
    authorize! :read, @buses
  end

  def new
    @bus = Bus.new
    authorize! :read, @bus
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @bus = current_user.buses.find_by_id(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @bus = current_user.buses.find_by_id(params[:id])
  end

  def create
    @bus = current_user.buses.create(bus_params)
    redirect_to buses_path(), notice:"Bus creates successfully!"
  end

  def update
    @bus = current_user.buses.find_by_id(params[:id])
    @bus.update(bus_params)
    redirect_to buses_path(), notice:"Bus update successfully!"
  end

  private 

  def bus_params
    params.require(:bus).permit(:bus_number, :bus_name, :total_seat, :image, bus_trips_attributes:[:id, :pickup_location, :destination_location, :distance, :departure, :_destroy])
  end
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/views/buses/_action.html.erb
<%= link_to "Show", bus_path(bus), class:"action btn btn-primary" %>
<%= link_to "Edit", edit_bus_path(bus), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class:"action btn btn-success" }%>
<%= link_to "Delete", bus_path(bus), class:"action btn btn-danger" %>

<%= link_to new_bus_driver_path(bus),{:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#bus-driver-#{bus.id}", class:"action btn btn-secondary"} do%>
<i class="fa fa-id-badge" aria-hidden="true"></i> Driver
<%end%>

<%= link_to bus.bus_service.present? ? edit_bus_bus_service_url(bus.bus_service, bus_id: bus.id) : new_bus_bus_service_path(bus),{:remote => true, 'data-toggle' =>  "modal", 'data-target' => "#bus-service-#{bus.id}", class:"action btn btn-secondary"} do%>
<i class="fa fa-cog" aria-hidden="true"></i> Services
<%end%>

app/views/buses/_bus_trip_fields.html.erb
<div class="nested-fields">
  <div class="form-group mb-3">
    <%= f.label :pickup_location, class: "mt-3" %>
    <%= f.collection_select :pickup_location, CS.cities(current_user.service_state.to_sym, :in), :itself, :itself, { prompt: "Select a pickup location" },class: 'mb-3 form-control'%>
  </div>

  <div class="form-group mb-3">
    <%= f.label :destination_location, class: "mt-3" %>
    <%= f.collection_select :destination_location, CS.cities(current_user.service_state.to_sym, :in), :itself, :itself, { prompt: "Select a pickup location" },class: 'mb-3 form-control'%>
  </div>

  <div class="form-group mb-3">
    <%= f.label :departure, class: "mt-3" %>
    <%= f.time_field :departure, class: 'mb-3 form-control'%>
  </div>

  <%= link_to_remove_association "Delete", f %>
</div>

app/views/buses/_edit_bus_seat.html.erb
<h5 class="text-center mb-5">Edit Bus Seat</h5>
<% @bus.seats.each do |seat|%>
  <div class="row">
    <div class="col-sm-6">
      <%= turbo_frame_tag "seat_name_#{seat.id}" do %>   
        <%= link_to seat.name, edit_seats_path(seat) %> 
      <% end %>
    </div>
    <div class="col-sm-6">
      <%= turbo_frame_tag "seat_type_#{seat.id}" do %>   
        <%= link_to seat.seat_type, edit_seats_path(seat) %> 
      <% end %>
    </div>
  </div>
<%end%>

app/views/buses/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add Bus Details</h4>
  <span type="button" class="close" style="font-size: 25px;" data-dismiss="modal">x</span>
</div>
<%= form_for @bus do |f|%>
  <div class="modal-body m-3">
    <div class="form-group mb-3">
      <%= f.label :bus_number %><br />
      <%= f.text_field :bus_number, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :bus_name %><br />
      <%= f.text_field :bus_name, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group mb-3">
      <%= f.label :total_seat %><br />
      <%= f.text_field :total_seat, autofocus: true, class: 'form-control' %>
    </div>

    <div class="form-group mb-3">
      <%= f.label :image %><br />
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="bus-trip">
      <fieldset>
        <legend>Bus Trip</legend>
        <div class="bus_trips">
          <%= f.fields_for :bus_trips do |bus_trip| %>
            <%= render 'bus_trip_fields', f: bus_trip %>
          <% end %>
        </div>
        <%= link_to_add_association "Add Trip", f, :bus_trips, data: {association_insertion_node: '.bus_trips', association_insertion_method: :append} %>
      </fieldset>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "save", class:"btn btn-primary"%>
  </div>
<%end%>

<script type="text/javascript">
  $(".close").click(function(){
    $("#modal-window").hide()
  });
</script>

app/views/buses/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'buses/new') %>");
// $("#modal-window").modal();
$("#modal-window").removeClass('hide');
$("#modal-window").show();
$("#modal-window").addClass('show');

app/views/buses/index.html.erb
<div class="container"> 
  <div class="mt-5 w-100">
    <h5 class="text-center">Add Your Bus</h5>
    <%= link_to new_bus_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do %>
    <div class="p-5 m-3 border-1 text-center bg-light add-bus">
      <i class="fa fa-plus" style="font-size: 40px; color: lightblue;" aria-hidden="true"></i>
    </div>
  <%end%>
  </div>

  <div class="mt-5">
    <h5 class="text-center">
      <i class="fa fa-bus" aria-hidden="true"></i> 
        Lists of buses
      <i class="fa fa-bus" aria-hidden="true"></i>
    </h5>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Bus Name</th>
          <th scope="col">Bus Number</th>
          <th scope="col">Total Seat</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @buses.each_with_index do |bus,index|%>
          <tr>
            <th scope="row"><%= index + 1%></th>
            <td><%= bus.bus_name%></td>
            <td><%= bus.bus_number%></td>
            <td><%= bus.total_seat%></td>
            <td>
               <%= render "buses/action", bus: bus%>
            </td>
          </tr>
          
          <!-- Add services -->
          <div id="bus-service-<%= bus.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content"></div>
            </div>
          </div>

          <!-- Add drivers -->
          <div id="bus-driver-<%= bus.id %>" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content"></div>
            </div>
          </div>
        <%end%>
      </tbody>
    </table>
  </div>


  <!-- Add buses -->

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
</div>

app/views/buses/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'buses/new') %>");
// $("#modal-window").modal();
$("#modal-window").removeClass('hide');
$("#modal-window").show();
$("#modal-window").addClass('show');

app/views/buses/show.html.erb
<div class="card m-5">
  <h5 class="card-header">Bus Details</h5>
  <div class="p-2">
    <button type="button" class="btn btn-outline-primary steps active" id="driver-button" onclick="myFunction('bus-driver','driver-button')">Bus Driver</button>
    <button type="button" class="btn btn-outline-primary steps" id="seat-button" onclick="myFunction('show-seats','seat-button')">Bus Seat</button>
    <button type="button" class="btn btn-outline-primary steps" id="servuce-button" onclick="myFunction('show-services','servuce-button')">Bus Services</button>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-8">
        <%= image_tag @bus.image, class:"w-75"%>
      </div>

      <div class="col-sm-4 common" id="bus-driver">
        <% if @bus.drivers.present? %>
          <%@bus.drivers.each do |driver|%>
            <div class="row p-3">
              <div class="row border shadow-lg p-2 bg-white rounded-top">
                <div class="col-sm-12 text-center">
                 <i class="fa fa-id-card" aria-hidden="true"></i> Drivering licence
               </div>
              </div>
              <div class="row border rounded-bottom shadow-lg p-3 bg-white">
                <div class="col-sm-4 p-2">
                  <%= image_tag driver.image, size:"100", class:"rounded"%>
                </div>

                <div class="col-sm-8 p-2">
                 <strong class="text-primary">Name: </strong><%= driver.name%></br>
                 <strong class="text-primary">Age: </strong><%= driver.age%></br>
                 <strong class="text-primary">License: </strong><%= driver.license%></br>
                 <strong class="text-primary">Contact No: </strong><%= driver.contact_no%></br>
                </div>
              </div>
            </div>
          <%end%>
        <%else%>
          <p class="text-center text-success">
            <i class="fa fa-info-circle" aria-hidden="true"></i> 
            Please Add Drivers For Your Bus!
          </p>
        <%end%>
      </div>

      <div class="col-sm-4 common text-center d-none" id="show-seats">
        <%if @bus.seats.present?%>
        <div class="edit-bus-<%= @bus.id%>-seat">
          <%= render "buses/edit_bus_seat"%>
        </div>
        <%else%>
          <p class="text-center text-success">
            <i class="fa fa-info-circle" aria-hidden="true"></i> 
            No Seat Available!
          </p>
        <%end%>
      </div>

      <div class="col-sm-4 common d-none" id="show-services">
        <%if @bus.bus_service.present?%>
          <h5 class="text-center mb-5">Bus Services</h5>
          <div class="">
            <%= get_services(@bus.bus_service).html_safe%>
          </div>
        <%else%>
          <p class="text-center text-success">
            <i class="fa fa-info-circle" aria-hidden="true"></i> 
            Bus Services Are Not Available!
          </p>
        <%end%>
      </div>
    </div>
    <div class="row">
      <h5 class="card-title"><%= @bus.bus_name%></h5>
      <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
</div>

<script type="text/javascript">
  function myFunction(params,id){
    var id = document.getElementById(id)
    var select_id = document.getElementById(params)
    // change active button
    document.querySelectorAll(".steps").forEach((formNavigationBtn) => {
      formNavigationBtn.classList.remove("active")
    });
    id.classList.add("active")

    // change button data
    document.querySelectorAll(".common").forEach((formNavigationBtn) => {
      formNavigationBtn.classList.add("d-none")
    });
    select_id.classList.remove("d-none")
    select_id.classList.add("d-block")
  }
</script>