config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
  resources :buses do
    resources :bus_services
    resources :drivers
  end
  resources :booking_seats do
    collection do
      get :sucess
      get :cancel
    end
  end
  get 'seats/show'
  patch 'seats/:id', to:"seats#update", as:"seat"
  get 'seats/:id/edit', to:"seats#edit", as:"edit_seats"
end

app/views/layouts/_header.html.erb
<div class="m-4">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand text-dark navbar-title" href="#">TechBus</a>
      <!-- <a href="#" class="navbar-brand">
          <img src="/examples/images/logo.svg" height="28" alt="CoolBrand">
      </a> -->
      <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">
            <%= link_to root_path(), class:"nav-item nav-link active" do%>
              <i class="fa fa-home" aria-hidden="true"></i> Home
            <%end%>
            <% if user_signed_in?%>
                <%= link_to buses_path(), class:"nav-item nav-link" do%>
                  <i class="fa fa-bus" aria-hidden="true"></i> Buses
                <%end%>
            <%end%>
        </div>
        <div class="navbar-nav ms-auto">
          <% if user_signed_in?%>
            <%= link_to destroy_user_session_path(), method: :delete, class:"nav-item nav-link" do%>
            Logout <i class="fa fa-sign-out" aria-hidden="true"></i>
            <span class="p-2"><i class="fa fa-globe" aria-hidden="true"></i> (<%= current_user.service_state%>)</span>
            <%end%>
          <%else%>
             <%= link_to "Login", new_user_session_path(), class:"nav-item nav-link"%>
             <%= link_to "SignUp", new_user_registration_path(), class:"nav-item nav-link"%>
          <%end%>
        </div>
      </div>
    </div>
  </nav>
</div>
<%#= form_tag("/", :method => "get", class:"form-inline d-flex") do %>
  <%#= text_field_tag :search,'',placeholder:"Search",class: "form-control mr-2" %>
  <%#= submit_tag "Search", class:"btn btn-outline-success" %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusBookingService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Hello User!</strong> <%= notice %>
      <span type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="fa fa-times-circle" aria-hidden="true"></i>
      </span>
    </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Hello User!</strong> <%= alert %>
      <span type="button" class="close" data-dismiss="alert" aria-label="Close">
        <i class="fa fa-times-circle" aria-hidden="true"></i>
      </span>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>